// nuxt/pages/login/index.vue
<template>
  <form @submit.prevent="submit" class="form login-form">
    <div class="form-component">
      <input name="username" type="text" v-model.lazy="username" placeholder="Username"/>
      <label>Username</label>
    </div>
    <div class="form-component">
      <input name="password" type="password" v-model.lazy="password" placeholder="Password"/>
      <label>Password</label>
    </div>
    <button type="submit">Login</button>
  </form>
</template>
<script src="./component.js"></script>
<style src="./styles.scss" lang="scss"></script>

// angular2/src/app/auth/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';

import { AuthApiService } from '../auth.api.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
  providers: [AuthApiService]
})
export class LoginComponent {
  public loginForm = this.fb.group({
    username: ["", Validators.required],
    password: ["", Validators.required]
  });

  constructor(public fb: FormBuilder, private service: AuthApiService) {}

  doLogin(event) {
    this.service.login(this.loginForm.value);
  }
}

<form [formGroup]="loginForm" (ngSubmit)="doLogin($event)" class="form login-form">
  <div class="form-component">
    <input name="username" type="text" formControlName="username" placeholder="Username"/>
    <label>Username</label>
  </div>
  <div class="form-component">
    <input name="password" type="password" formControlName="password" placeholder="Password"/>
    <label>Password</label>
  </div>
  <button type="submit">Login</button>
</form>
