// angular2/src/app/tasks/task-input/task-input.component.ts
import { Component } from '@angular/core';

import { TasksApiService } from '../tasks.api.service';

@Component({
  selector: 'task-input',
  templateUrl: './task-input.component.html',
  styleUrls: ['./task-input.component.scss']
})
export class TaskInputComponent {
  constructor (private service: TasksApiService) {}

  onEnter (description) {
    this.service.addTask(description);
  }
}

<div class="task-input-container">
  <input
    name="newTask"
    type="text"
    (keyup.enter)="onEnter($event.target.value); $event.target.value='';"
    placeholder="What needs to be done?"/>
</div>

// nuxt/components/task-input/index.vue
<template>
  <div class="task-input-container">
    <input
      name="newTask"
      type="text"
      v-model.lazy="description"
      @keyup.enter="addNewTask"
      placeholder="What needs to be done?"/>
  </div>
</template>
<script src="./component.js"></script>
<style src="./styles.scss" lang="scss"></style>
