// nuxt/components/task-item/index.vue
<template>
  <div class="task-item task-item-container" :class="{active: task.active}">
    <div class="actions actions-left">
    </div>
    <div class="item-description">{{ task.description }}</div>
    <div class="actions actions-right">
      <a class="action item-delete" @click="deleteTask"></a>
    </div>
    <input
      name="description"
      type="text"
      class="task-item-input"
      :class="{hidden: !task.editMode}"
      v-model="task.description"
      @keyup.enter="updateDescription"
    />
  </div>
</template>
<script src="./component.js"></script>
<style src="./styles.scss" lang="scss"></style>

// angular2/src/app/tasks/task-item/task-item.component.ts
import { Component, Input } from '@angular/core';

import { TaskApiService } from '../tasks.api.service';
import { TaskActions } from '../tasks.actions';

import { ITask } from '../tasks.model';

@Component({
  selector: 'task-item',
  templateUrl: './task-item.component.html',
  styleUrls: ['./task-item.component.scss']
})
export class TaskItemComponent {
  @Input() task: ITask

  constructor (private service: TaskApiService, private actions: TaskActions) {}

  deleteTask (id) {
    this.service.deleteTask(id);
  }

  changeStatus (task) {
    task.active = !task.active;

    this.service.updateTask(task);
  }

  editTask (task, input) {
    this.actions.changeEditMode(task.id, true);

    input.value = task.description;

    setTimeout(() => {
      input.focus();
    }) ;
  }

  updateDescription (task, description) {
    task.editMode = false;
    task.description = description;
    this.service.updateTask(task);
  }
}

<div class="task-item task-item-container" [ngClass]="{'active': task.active}">
  <div class="actions actions-left">
      <a class="action item-change-status" (click)="changeStatus(task)"></a>
  </div>
  <div class="item-description">{{task.description}}</div>
  <div class="actions actions-right">
      <a class="action item-edit" (click)="editTask(task, taskEditInput);" [ngClass]="{'hidden': !task.active}"></a>
      <a class="action item-delete" (click)="deleteTask(task.id)"></a>
  </div>
  <input
    #taskEditInput
    name="description"
    type="text"
    class="task-item-input"
    [ngClass]="{'hidden': !task.editMode}"
    (keyup.enter)="updateDescription(task, taskEditInput.value)"/>
</div>
